class BaseHTTPServer implements IHTTPServer{
    + const string VERSION
    + const string NAME
    - int port
    - bool running
    - TcpListener listener
    - List<IResourceEndpointHandler> resourceEndpointHandlers

    + BaseHTTPServer(int port)
    + void Start()
    - void Run()
    - void HandleClient(TcpClient client)
}

class RequestContext{
    + String Type {get;set;}
    + String URL {get;set;}
    + String HTTPVersion {get;set;}
    + List<HttpHeaderPair> HeaderPairs {get;private set;}
    + String Body {get;set;}

    + void AddHeader(String headerLine)
    + static RequestContext GetBaseRequest(String request)
    + override string ToString()
    - RequestContext(String type, String url, String httpVersion)
}

class HttpHeaderPair{
    + String HeaderKey {get;set;}
    + String HeaderValue {get;set;}

    + HttpHeaderPair(String headerKey, String headerValue)
    + override string ToString()
}

interface IResourceEndpointHandler{
    + bool CheckResponsibility(RequestContext requestContext)
    + void HandleRequest(RequestContext requestContext)
}

interface ICRUDHandler{
    + void ListHandler(RequestContext requestContext, NetworkStream networkStream)
    + void CreateHandler(RequestContext requestContext, NetworkStream networkStream)
    + void ReadHandler(RequestContext requestContext, NetworkStream networkStream)
    + void UpdateHandler(RequestContext requestContext, NetworkStream networkStream)
    + void DeleteHandler(RequestContext requestContext, NetworkStream networkStream)
}

class MessageResourceEndpointHandler implements IResourceEndpointHandler, ICRUDHandler{
    - List<Message> _messages
    - const String urlBase
    - List<RouteAction> RouteActions
    - int nextId;

    + MessageResourceEndpointHandler()
    - RouteAction DetermineRouteAction(RequestContext requestContext)
    - void SendResponse(ResponseContext responseContext, NetworkStream networkStream)
}
 class RouteAction{
     + String PathRegex {get;set;}
     + Action<RequestContext, NetworkStream> PathAction {get;set;}
     + String RequestType {get;set;}

     + RouteAction(IAction<RequestContext, NetworkStream> pathAction, String pathRegex, String requestType)
 }

 class Message{
     + int Id {get;set;}
     + String Content {get;set;}
     + DateTime SentDate {get;set;}

     + override string ToString()
 }

class ResponseContext{
    + String HTTPVersion {get;set;}
    + String StatusMessage {get;set}
    + int StatusCode {get;set}
    + List<HttpHeaderPair> HeaderPairs {get;private set;}
    + String Content {get;private set;}

    + static ResponseContext OKResponse()
    + static ResponseContext CreatedResponse()
    + static ResponseContext NotFoundResponse()
    + static ResponseContext BadRequestResponse()
    + ResponseContext AddHeader(HttpHeaderPair httpHeaderPair)
    + ResponseContext SetContent(String content, String contentType)
    + override string ToString()
    - ResponseContext(String httpVersion, String statusMessage, int statusCode)
}

interface IHTTPServer{
    + void Start()
}


 BaseHTTPServer o-- IResourceEndpointHandler
 RequestContext o-- HttpHeaderPair
 MessageResourceEndpointHandler o-- RouteAction
 MessageResourceEndpointHandler o--Message
 MessageResourceEndpointHandler ..> ResponseContext
 MessageResourceEndpointHandler ..> RequestContext
 ResponseContext o-- HttpHeaderPair